CREATE TABLE IF NOT EXISTS products(
	id VARCHAR(20) NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE,
	price DOUBLE PRECISION NOT NULL,
	quantity SMALLINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);